// <auto-generated />
namespace MeusProtocolos.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class Relacionamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relacionamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201910190432160_Relacionamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
